theme: jekyll-theme-chirpy

lang: en
timezone: Europe/Warsaw

title: Around IT in 256 seconds
tagline: By Tomasz Nurkiewicz
description: >-
  Podcast for developers, testers, SREs… and their managers. I explain complex
  and convoluted technologies in a clear way, avoiding buzzwords and hype.
  Never longer than 4 minutes and 16 seconds.

url: https://nurkiewicz.com
baseurl: ""
repository: nurkiewicz/nurkiewicz.com

github:
  username: nurkiewicz
twitter:
  username: tnurkiewicz
social:
  name: Tomasz Nurkiewicz
  fediverse_handle: "@nurkiewicz@fosstodon.org"
  links:
    - https://github.com/nurkiewicz
    - https://www.linkedin.com/in/tomasz-nurkiewicz-80513b92/
    - https://fosstodon.org/@nurkiewicz
    - https://pixelfed.social/nurkiewicz

avatar: /assets/img/cover.jpg
social_preview_image: /assets/img/cover.jpg

analytics:
  google:
    id: G-K7V9PZ2DFN

theme_mode:
toc: true
actions:
  edit_post:
    enabled: true
    url: https://github.com/nurkiewicz/nurkiewicz.com/edit/master/docs
    static_url: false

comments:
  provider: utterances
  utterances:
    repo: nurkiewicz/nurkiewicz.com
    issue_term: "og:title"

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:
      - /10x10
      - /slides

paginate: 50

feed:
  path: feeds/posts/default

permalink: /:year/:month/:title:output_ext

kramdown:
  input: GFM
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      toc: true
      comments: true
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

include:
  - _next
